version: "0.5"

processes:
  nijiiro:
    command: "nix develop -c deno task start"
    working_dir: "/home/maril/workspace/nijiiro"
    log_location: /home/maril/nijiiro.log
    availability:
      restart: "on_failure"
      max_restarts: 3
  n-high-lovelive:
    command: "nix develop -c crystal run --release src/n-high-lovelive.cr"
    working_dir: "/home/maril/workspace/n-high-lovelive"
    log_location: /home/maril/n-high-lovelive.log
    availability:
      restart: "on_failure"
      max_restarts: 3
